# -*- coding: utf-8 -*-
"""Batch-generate Certificate Maker SEO pages — DIFFERENTIATED content.
Each page leads with copy-paste WORDS for that certificate type (the real
search intent), then type-specific fields + varied tips. No two pages share
the same skeleton. Run with `py gen_seo_batch.py`."""
import os

OUT = r'D:\claude\certificate-maker\seo'
os.makedirs(OUT, exist_ok=True)

BASE = 'https://aiharryone.github.io/certificate-maker'

HEAD = '''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="msvalidate.01" content="E62785F51D89A3BD3AFBB2BC2BB07BF9">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<meta name="description" content="{meta}">
<link rel="canonical" href="{base}/seo/{slug}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Certificate Maker">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{meta}">
<meta property="og:url" content="{base}/seo/{slug}">
<script type="application/ld+json">
{ldjson}
</script>
<style>
  *{margin:0;padding:0;box-sizing:border-box;}
  body{font-family:'Trebuchet MS','Segoe UI',sans-serif;background:#f4f7fb;color:#2c3e50;line-height:1.7;}
  .wrap{max-width:880px;margin:0 auto;padding:0 22px;}
  header{background:linear-gradient(135deg,#3a7bd5,#00d2ff);color:#fff;padding:18px 0;}
  nav{display:flex;justify-content:space-between;align-items:center;}
  .logo{font-weight:bold;font-size:21px;}
  .nav-links a{color:#fff;text-decoration:none;font-weight:bold;margin-left:18px;}
  .btn{display:inline-block;background:#fff;color:#2c6ab3;text-decoration:none;padding:11px 26px;border-radius:30px;font-weight:bold;transition:.15s;border:none;cursor:pointer;}
  .btn:hover{background:#eef5ff;}
  .hero{text-align:center;padding:46px 0 26px;}
  .hero h1{font-size:34px;color:#2c3e50;margin-bottom:12px;letter-spacing:-.5px;}
  .hero p{font-size:17px;color:#7a8ea8;max-width:640px;margin:0 auto;}
  .hero .answer{background:#fff;border-left:4px solid #3a7bd5;border-radius:8px;padding:12px 16px;max-width:680px;margin:16px auto 0;text-align:left;font-size:15px;color:#2c3e50;box-shadow:0 4px 14px rgba(58,123,213,.1);}
  .hero .answer b{color:#3a7bd5;}
  .hero .sub{font-size:14px;color:#93a5bd;margin-top:12px;}
  section{padding:26px 0;}
  h2{color:#3a7bd5;margin-bottom:14px;font-size:24px;}
  .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:16px;}
  .card{background:#fff;border-radius:14px;padding:20px;box-shadow:0 4px 14px rgba(58,123,213,.1);}
  .card h3{color:#3a7bd5;margin-bottom:6px;font-size:17px;}
  .card p{font-size:15px;}
  ul.tips{margin:8px 0 8px 22px;}
  ul.tips li{margin:8px 0;}
  ol.steps{margin:8px 0 8px 22px;}
  ol.steps li{margin:8px 0;}
  .example{background:#fff;border-radius:14px;padding:18px 22px;box-shadow:0 4px 14px rgba(58,123,213,.1);margin-bottom:14px;}
  .example b{color:#3a7bd5;}
  .quote{background:#eef5ff;border-left:4px solid #3a7bd5;border-radius:8px;padding:12px 18px;margin-bottom:10px;font-size:15px;color:#2c3e50;}
  .quote i{color:#5a7ea0;}
  .cta{text-align:center;background:linear-gradient(135deg,#3a7bd5,#00d2ff);color:#fff;border-radius:16px;padding:38px 24px;margin:22px 0;}
  .cta h2{color:#fff;margin-bottom:10px;}
  .cta p{margin-bottom:20px;font-size:16px;opacity:.95;}
  .faq p{margin-bottom:10px;background:#fff;border-radius:10px;padding:14px 18px;}
  .faq b{color:#2c6d8f;}
  .related{margin-top:34px;background:#fff;border-radius:14px;box-shadow:0 4px 14px rgba(58,123,213,.1);padding:24px;}
  .related h2{font-size:20px;margin-bottom:12px;}
  .related a{display:inline-block;background:#eef5ff;color:#2c6ab3;border-radius:20px;padding:6px 14px;margin:4px 6px 0 0;text-decoration:none;font-size:14px;font-weight:bold;}
  footer{background:#2c3e50;color:#a8bdc9;padding:24px 0;text-align:center;font-size:13px;margin-top:36px;}
  footer a{color:#7ec8e3;text-decoration:none;}
  @media(max-width:600px){.hero h1{font-size:27px;}.btn{display:block;margin:8px 0;text-align:center;}}
</style>
<!-- Cloudflare Web Analytics --><script type='module' src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "26b749ec88b5405bb9524de7d3deb750"}'></script><!-- End Cloudflare Web Analytics -->
</head>
<body>
<header>
  <div class="wrap nav">
    <div class="logo">🏆 Certificate Maker</div>
    <div class="nav-links">
      <a href="{base}/index.html">Maker</a>
      <a href="{base}/certificate-of-completion-template.html">Completion</a>
      <a class="btn" href="{base}/index.html">Make One Free →</a>
    </div>
  </div>
</header>

<div class="wrap">
  <div class="hero">
    <h1>{h1}</h1>
    <p>{hero_p}</p>
    <p class="answer"><b>Short answer:</b> {tldr}</p>
    <p class="sub">Free in your browser · No signup · Printable · Updated 2026</p>
  </div>

  {sections}

  <div class="cta">
    <h2>{cta_h2}</h2>
    <p>{cta_p}</p>
    <a class="btn" href="{base}/index.html" style="font-size:16px;">Make Your Certificate Now — Free →</a>
  </div>

  <div class="related">
    <h2>More Certificate Templates</h2>
    {related}
    <p style="margin-top:14px;font-size:13px;color:#93a5bd;">Everything is made in your browser — nothing is uploaded, no account needed.</p>
  </div>
</div>

<footer>
  <p>Made for teachers, trainers and creators who value beautiful certificates. Questions? Ai_harryone@outlook.com · <a href="{base}/index.html">Certificate Maker</a> · <a href="{base}/privacy.html">Privacy</a> · <a href="{base}/terms.html">Terms</a></p>
  <p style="margin-top:8px;font-size:12px;opacity:.75;">Last updated: September 1, 2026</p>
</footer>
</body>
</html>
'''

def faq_block(items):
    return '<section class="faq">\n<h2>FAQ</h2>\n%s</section>' % ''.join('<p><b>%s</b> %s</p>' % (q, a) for q, a in items)

def ldjson(items):
    qa = []
    for q, a in items:
        qa.append('{"@type":"Question","name":"%s","acceptedAnswer":{"@type":"Answer","text":"%s"}}' % (q.replace('"', '\\"'), a.replace('"', '\\"')))
    return '{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[%s]}' % ','.join(qa)

def sec(title, body):
    return '<section>\n<h2>%s</h2>\n%s\n</section>' % (title, body)

def card(h3, p):
    return '<div class="card"><h3>%s</h3><p>%s</p></div>' % (h3, p)

def words(items):
    """Render copy-paste wording blocks: list of (tone, phrase)."""
    return ''.join('<div class="quote"><b>%s</b><br><i>%s</i></div>' % (tone, phrase) for tone, phrase in items)

def _ld_for(sections):
    import re
    faq_section = [s for s in sections if s.startswith('<section class="faq">')]
    if not faq_section:
        return ''
    items = re.findall(r'<p><b>(.*?)</b> (.*?)</p>', faq_section[0])
    return ldjson(items)

def build(slug, title, meta, h1, hero, wording_label, wording, fields, fields_title, tip_title, tips, faq, cta_h2, cta_p, extra=None, steps=None, tool='index.html', tool_name='Certificate Maker'):
    """Build a differentiated page: wording first, then fields, tips, tool steps, FAQ."""
    sections = [sec(wording_label, words(wording))]
    if fields:
        sections.append(sec(fields_title or 'What to Put on Your Certificate', '<ul class="tips">%s</ul>' % ''.join('<li>%s</li>' % x for x in fields)))
    if tips:
        sections.append(sec(tip_title or 'Tips That Make It Feel Real', '<ul class="tips">%s</ul>' % ''.join('<li>%s</li>' % x for x in tips)))
    if extra:
        sections.append(sec(extra[0], extra[1]))
    if steps is None:
        steps = ['Open <a href="{base}/%s" style="color:#2c6ab3;font-weight:bold;">%s</a>.' % (tool, tool_name),
                 'Pick this template and type the name, reason and date.',
                 'Paste one of the wordings above into the description.',
                 'Download a print-ready PNG.']
    sections.append(sec('Make It in Your Browser in 30 Seconds', '<ol class="steps">%s</ol>' % ''.join('<li>%s</li>' % x for x in steps)))
    sections.append(faq_block(faq))
    return {'slug': slug, 'title': title, 'meta': meta, 'h1': h1, 'hero_p': hero, 'sections': sections, 'cta_h2': cta_h2, 'cta_p': cta_p}

PAGES = [
  build('award-certificate-template.html',
    'Award Certificate Template + Wording to Copy (Free)',
    'Award certificate template with ready-to-copy wording: employee, student and sports awards. Edit in your browser and print. Free, nothing uploaded.',
    'Award Certificate Template & Wording',
    'A template plus the exact wording that makes an award feel earned.',
    'Copy-Paste Award Wording',
    [('Formal award', 'This certificate is proudly presented to [Name] for outstanding performance and achievement.'),
     ('Specific / results', 'Awarded to [Name] for exceeding the [quarter] sales target by [120]% and delivering [milestone].'),
     ('Project completion', 'Presented to [Name] in recognition of exceptional leadership in the successful completion of [Project], delivered on time and on budget.'),
     ('Academic', 'Awarded to [Name] for outstanding academic achievement in [Subject] during [Term/Year].'),
     ('Short (plaques & digital)', 'For leadership, teamwork, and consistent professionalism.'),
     ('Warm', 'Congratulations on this milestone — you worked hard for it, and it shows.')],
    ['<b>Name</b> — the centerpiece, spelled exactly right.',
     '<b>Award reason</b> — name the specific result, not “a great job”.',
     '<b>Date & organization</b> — who is awarding and when.',
     '<b>Signature + title</b> — an authorized signature line adds weight.'],
    'What to Put on an Award Certificate',
    'Make It Feel Earned',
    ['<b>Numbers beat adjectives</b> — “exceeded target by 120%” lands harder than “outstanding”.',
     '<b>One accent color</b> — a gold or navy border reads formal without clutter.',
     '<b>Proofread the name</b> — a misspelled recipient is the one mistake everyone notices.'],
    [('Is it free?','Yes — the free template is free to use; premium unlocks for a one-time $9.99.'),
     ('Can I edit the wording?','Yes — every field is editable, and you can paste any of the wordings above.'),
     ('Can I print it?','Yes — download a high-res PNG and print at any size.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make an Award Certificate Now.',
    'Free to try — no signup, nothing uploaded.'),

  build('certificate-generator-online-free.html',
    'Certificate Generator Online — Free, With Built-in Wording',
    'A free online certificate generator that writes the wording for you: pick a type, get copy-paste text, edit in your browser and download. Nothing uploaded.',
    'Certificate Generator Online',
    'Type the details, pick the wording, download a print-ready certificate.',
    'Wording the Generator Can Use',
    [('Completion', 'This certifies that [Name] has successfully completed [Program] on [Date].'),
     ('Achievement', 'Awarded to [Name] in recognition of exceptional effort and achievement in [Program].'),
     ('Participation', 'This certificate is presented to [Name] for participating in [Event] on [Date].'),
     ('Recognition', 'Presented to [Name] for outstanding contribution to [Team/Project] during [Period].'),
     ('Appreciation', 'With sincere gratitude to [Name] for [contribution], [Date].'),
     ('Formal', 'This is to certify that [Name] has successfully completed [Course] with [Hours] hours of study.')],
    ['<b>Header line</b> — “This certifies that” vs “Awarded to” sets the formality.',
     '<b>Recipient</b> — full name, prominent.',
     '<b>Reason</b> — 2–4 sentences max; the certificate is the artifact, not the transcript.',
     '<b>Date + signatory</b> — both anchor authenticity.'],
    'What a Good Certificate Contains',
    'Avoid These Pitfalls',
    ['<b>Vague reasons</b> — “for participation in our program” (which program? when?).',
     '<b>Missing fields</b> — no date, organization or signatory makes it feel fake.',
     '<b>Passive overload</b> — “It is hereby certified that completion has been made” → “This certifies that [Name] completed…”.'],
    [('Is it really free?','Yes — the free template is free; premium is a one-time $9.99 unlock.'),
     ('Do I need to sign up?','No — no account, no email.'),
     ('What can I download?','A print-ready PNG at 1200×850.'),
     ('Is my data uploaded?','No — everything is generated in your browser.')],
    'Generate a Certificate Now.',
    'Free to try — no signup, nothing uploaded.'),

  build('recognition-certificate-template.html',
    'Recognition Certificate Template + Employee Wording',
    'Recognition certificate template with employee wording to copy: team, milestone and years-of-service awards. Edit and print free in your browser.',
    'Recognition Certificate Template',
    'Recognize real work with wording that names exactly what they did.',
    'Copy-Paste Recognition Wording',
    [('Team milestone', 'Presented to [Name] for outstanding contribution to [Team] during [Period].'),
     ('Years of service', 'This certificate recognizes [Name] for [5] years of dedicated service to [Company].'),
     ('Project success', 'In recognition of [Name]\'s leadership and execution in delivering [Project] ahead of schedule.'),
     ('Peer / colleague', 'Awarded to [Name] with appreciation from [Team] for going above and beyond on [Initiative].'),
     ('Formal corporate', 'For exemplary performance and contribution to [Department] in [Year].')],
    ['<b>Employee name</b> — the reason the certificate gets framed.',
     '<b>The specific contribution</b> — project, quarter, result.',
     '<b>Company + logo</b> — makes it feel official.',
     '<b>Date + signature</b> — adds weight.'],
    'What to Put on a Recognition Certificate',
    'Wording Tips',
    ['<b>Say the result, not the effort</b> — “delivered 14 new enterprise clients” beats “hard worker”.',
     '<b>Time periods anchor it</b> — “during Q3” makes it real.',
     '<b>Keep it 2–4 sentences</b> — the certificate is the artifact, the story belongs in the speech.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I add a company logo?','Yes — upload your logo in the editor.'),
     ('Can I print it?','Yes — high-res PNG download.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Recognition Certificate Now.',
    'Free to try — no signup, nothing uploaded.'),

  build('participation-certificate-template.html',
    'Participation Certificate Template + Event Wording (Free)',
    'Participation certificate template with ready-to-copy event wording: webinars, workshops, classes. Generate many fast, print and hand out. Free.',
    'Participation Certificate Template',
    'Thank every attendee with a clean certificate you can batch in minutes.',
    'Copy-Paste Participation Wording',
    [('Event', 'This certificate is presented to [Name] for participating in [Event] on [Date].'),
     ('Webinar', 'For attending the [Webinar] webinar on [Date] — thanks for showing up and engaging.'),
     ('Workshop', 'For completing the [Workshop] workshop and joining [Hours] hours of hands-on learning.'),
     ('Warm', 'For showing up, giving your best and being part of what made [Event] special.'),
     ('Short', 'For participating in [Event], [Date].')],
    ['<b>Participant name</b> — the personal touch.',
     '<b>Event + date</b> — what they attended and when.',
     '<b>Your organization</b> — who is certifying.',
     '<b>Keep it clean</b> — a participation certificate should feel generous, not formal.'],
    'What to Include',
    'If You Are Handing Out Many',
    ['<b>Lock the wording once</b> — identical text except the name keeps the batch clean.',
     '<b>Fill names one by one</b> — each takes ~30 seconds in the browser.',
     '<b>Print on card stock</b> — a stack of 30 cards feels like an event.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I make many at once?','Each takes ~30 seconds; generate as many as you need.'),
     ('Can I print them?','Yes — print-ready high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Participation Certificate Now.',
    'Free to try — no signup.'),

  build('graduation-certificate-template.html',
    'Graduation Certificate Template + Formal Wording (Free)',
    'Graduation certificate template with formal wording to copy: courses, bootcamps, summer programs. Edit, print and present. Free in your browser.',
    'Graduation Certificate Template',
    'Wording that turns “you finished” into “you achieved”.',
    'Copy-Paste Graduation Wording',
    [('Course completion', 'This certifies that [Name] has successfully completed the [Program] and is hereby awarded this Certificate of Completion.'),
     ('Bootcamp / intensive', 'For successfully completing [Bootcamp], a [10]-week intensive program, on [Date].'),
     ('Academic', 'Presented to [Name] in recognition of outstanding academic achievement in [Subject] during [Term].'),
     ('Formal', 'This is to certify that [Name] has fulfilled all requirements of [Program] and is entitled to this certificate.'),
     ('Warm', 'Congratulations, [Name] — you showed up, put in the work, and finished.')],
    ['<b>Graduate name</b> — prominent and elegant.',
     '<b>Program name</b> — exactly what they completed.',
     '<b>Date of completion</b> — the milestone.',
     '<b>Instructor / institution</b> — the authority behind it.'],
    'What to Include',
    'Make It Feel Like a Milestone',
    ['<b>Formal phrasing</b> — “This certifies that” beats “Congrats!” for a graduation.',
     '<b>Add duration if true</b> — “a 10-week intensive” adds credibility.',
     '<b>Seal or border</b> — a formal border makes it feel like a diploma.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit all the text?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG, print at any size.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Graduation Certificate Now.',
    'Free to try — no signup.'),

  build('certificate-of-achievement-template.html',
    'Certificate of Achievement Template + Wording (Free)',
    'Certificate of achievement template with ready-to-copy wording for students, employees and athletes. Edit and print free in your browser.',
    'Certificate of Achievement Template',
    'A template plus the wording that makes an achievement permanent.',
    'Copy-Paste Achievement Wording',
    [('Standard', 'Awarded to [Name] in recognition of exceptional effort and achievement in [Program].'),
     ('Academic', 'For outstanding academic achievement in [Subject] during [Term] at [Institution].'),
     ('Specific result', 'For achieving [grade / rank / result] in [Competition] on [Date].'),
     ('Corporate', 'For exemplary performance in [Role] and contribution to [Department] in [Year].'),
     ('Motivational', 'In recognition of [Name]\'s dedication, perseverance and achievement in [Program].'),
     ('Short', 'For academic achievement and a strong commitment to learning.')],
    ['<b>Name of the achiever</b> — the centerpiece.',
     '<b>The specific achievement</b> — grade, record, result.',
     '<b>Date</b> — anchors the moment.',
     '<b>Signature or seal</b> — makes it feel official.'],
    'What to Put on the Certificate',
    'Wording Tips',
    ['<b>Be specific</b> — “for ranking first in the class” beats “for doing great”.',
     '<b>Match tone to audience</b> — formal for academic/corporate, warm for kids.',
     '<b>Keep it to 2–4 sentences</b> — the certificate is the artifact, not the transcript.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable in your browser.'),
     ('Can I print it?','Yes — print-ready high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make an Achievement Certificate Now.',
    'Free to try — no signup.'),

  build('appreciation-certificate-template.html',
    'Appreciation Certificate Template + Thank-You Wording',
    'Appreciation certificate template with warm thank-you wording: volunteers, staff, mentors, donors. Edit and print free in your browser.',
    'Appreciation Certificate Template',
    'A thank-you that lasts — wording that feels sincere, not corporate.',
    'Copy-Paste Appreciation Wording',
    [('Volunteer', 'With sincere gratitude to [Name] for [Hours] hours of service to [Organization].'),
     ('Staff', 'Presented to [Name] in recognition of [Years] years of dedication to [Company].'),
     ('Mentor', 'Thank you, [Name], for the guidance and generosity you gave [Person/Team].'),
     ('Donor', 'With deep appreciation for [Name]\'s generosity in supporting [Cause].'),
     ('Warm', 'For making a real difference and doing it with grace — thank you.'),
     ('Formal', 'In recognition of [Name]\'s outstanding contribution and dedication.')],
    ['<b>Name</b> — appreciation is personal.',
     '<b>The specific contribution</b> — hours, years, cause.',
     '<b>Your organization</b> — who is saying thanks.',
     '<b>A warm closing</b> — “With sincere gratitude”.'],
    'What to Include',
    'Make It Feel Sincere',
    ['<b>Be specific about the contribution</b> — “120 hours of community service” is real.',
     '<b>Warm beats formal</b> — appreciation certificates should feel grateful, not contractual.',
     '<b>A gold accent</b> — a touch of gold reads as honor, not corporate.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I add a message?','Yes — you control all the text.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make an Appreciation Certificate Now.',
    'Free to try — no signup.'),

  build('blank-certificate-template-printable.html',
    'Blank Certificate Template — Printable, Fillable & Reusable',
    'Blank certificate templates you can print and fill by hand or reuse: awards, events, classrooms. Make one in your browser and print any number. Free.',
    'Blank Certificate Template',
    'A clean printable layout for handwritten names — or a reusable design.',
    'Blank Certificate Wording Ideas',
    [('If filling by hand', 'This certificate is awarded to ______________ for ______________ on ______________.'),
     ('Award', 'Presented to ______________ in recognition of ______________.'),
     ('Classroom', 'This certifies that ______________ has completed ______________.'),
     ('Participation', 'Thank you for being part of ______________ on ______________.'),
     ('Generic', 'In recognition of ______________\'s contribution and dedication.')],
    ['<b>Leave the name blank</b> — for handwritten fills.',
     '<b>Keep a clean layout</b> — a blank design should still look finished.',
     '<b>Add a signature line</b> — usable by any signer.',
     '<b>Print as many as you need</b> — the same design, filled differently every time.'],
    'What a Good Blank Has',
    'How to Use It',
    ['<b>Print a stack before the event</b> — fill names in pen on the spot.',
     '<b>Or type and regenerate</b> — each takes ~30 seconds.',
     '<b>Card stock</b> — a blank you fill by hand still deserves good paper.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I print a blank?','Yes — just leave the name empty and print.'),
     ('Can I fill it by hand?','Yes — or type names and regenerate.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Blank Certificate Now.',
    'Free to try — no signup.'),

  build('course-completion-certificate-template.html',
    'Course Completion Certificate Template + Wording (Free)',
    'Course completion certificate template with wording that adds credibility: hours, level, instructor. For online courses and training. Free.',
    'Course Completion Certificate Template',
    'A certificate that makes your course feel worth finishing.',
    'Copy-Paste Course Completion Wording',
    [('Standard', 'This certifies that [Name] has successfully completed [Course] on [Date].'),
     ('With hours', 'For completing [Course], a [10]-hour program, and passing the final assessment.'),
     ('With level', 'For successfully completing [Course] at the [Intermediate] level.'),
     ('Formal', 'This is to certify that [Name] has fulfilled all requirements of [Course] and is awarded this certificate.'),
     ('Warm', 'Congratulations, [Name] — you finished [Course], and we\'re proud of the work you put in.')],
    ['<b>Student name</b> — the credential they show employers.',
     '<b>Course title</b> — exactly what they completed.',
     '<b>Hours or level</b> — adds credibility.',
     '<b>Instructor + date</b> — authority and timing.'],
    'What to Include for Credibility',
    'Why Certificates Help Courses',
    ['<b>They convert</b> — students finish courses that offer a certificate.',
     '<b>They\'re shareable</b> — a PNG is easy to add to LinkedIn and resumes.',
     '<b>They brand you</b> — a clean certificate makes your course feel more professional than a PDF they could fake.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I add my course branding?','Yes — upload your logo and set your colors.'),
     ('Can I batch them?','Each takes ~30 seconds; generate one per student.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Course Completion Certificate Now.',
    'Free to try — no signup.'),

  build('employee-of-the-month-certificate.html',
    'Employee of the Month Certificate + Wording (Free)',
    'Employee of the month certificate template with wording: name the month, the reason, the results. Edit and print free in your browser.',
    'Employee of the Month Certificate',
    'Wording that makes monthly recognition worth framing.',
    'Copy-Paste Employee of the Month Wording',
    [('Standard', 'Presented to [Name] as Employee of the Month for [Month Year].'),
     ('With reason', 'In recognition of [Name]\'s outstanding performance and positive impact during [Month Year].'),
     ('With results', 'Awarded to [Name] for delivering [result] and embodying [value] in [Month Year].'),
     ('Team', 'Voted by [Team] for going above and beyond in [Month Year].'),
     ('Formal', 'For exceptional service, professionalism and dedication to [Company] during [Month Year].')],
    ['<b>Employee name</b> — the centerpiece.',
     '<b>Month and year</b> — makes it a collectible.',
     '<b>The reason</b> — result, value, or team vote.',
     '<b>Company + signature</b> — official and personal.'],
    'What to Include',
    'Make It a Real Program',
    ['<b>Name the month</b> — a dated certificate becomes a series people collect.',
     '<b>Say why</b> — “for delivering X” makes it meaningful, not token.',
     '<b>Print and frame it</b> — a certificate on the wall is visible recognition every day.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I add a company logo?','Yes — upload it in the editor.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make an Employee of the Month Certificate Now.',
    'Free to try — no signup.'),

  build('teacher-appreciation-certificate.html',
    'Teacher Appreciation Certificate + Wording (Free)',
    'Teacher appreciation certificate with warm wording for students, classes and school boards. Edit and print free in your browser.',
    'Teacher Appreciation Certificate',
    'A thank-you a teacher will keep for years.',
    'Copy-Paste Teacher Appreciation Wording',
    [('From a student', 'Thank you, [Teacher], for making [Subject] the best part of my day.'),
     ('From a class', 'Presented with gratitude by the [Grade/Class] to [Teacher] for inspiring a love of learning.'),
     ('From the school', 'In recognition of [Teacher]\'s outstanding dedication to teaching at [School].'),
     ('Warm', 'For every extra hour, every patient explanation and every student who felt seen — thank you.'),
     ('Formal', 'For exceptional commitment to student growth and education during [School Year].')],
    ['<b>Teacher name</b> — the reason this is special.',
     '<b>Why</b> — “for inspiring a love of learning”.',
     '<b>From whom</b> — a student, a class, or the school.',
     '<b>Date</b> — the year of the thank-you.'],
    'What to Include',
    'Make It Memorable',
    ['<b>A student\'s words hit hardest</b> — one specific sentence beats a generic line.',
     '<b>Add the class year</b> — teachers keep these for decades.',
     '<b>Warm and simple</b> — a heartfelt certificate needs no corporate polish.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit the message?','Yes — all text is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Teacher Appreciation Certificate Now.',
    'Free to try — no signup.'),

  build('sports-award-certificate.html',
    'Sports Award Certificate Template + Wording (Free)',
    'Sports award certificate template with ready-to-copy MVP, champion and sportsmanship wording. For teams and leagues. Free in your browser.',
    'Sports Award Certificate',
    'MVP, champion, most improved — wording for every role on the team.',
    'Copy-Paste Sports Award Wording',
    [('MVP', 'For being the Most Valuable Player at the [Year] [Tournament]. Your skill, leadership and impact decided every game.'),
     ('Champion', 'Presented to [Name] for leading [Team] to the [Year] [Division] Championship.'),
     ('Most improved', 'For the most dramatic improvement this season — from [benchmark] to [benchmark].'),
     ('Sportsmanship', 'For demonstrating fair play, respect for opponents and grace under pressure at [Event].'),
     ('Participation', 'For showing up, giving your best and being a great teammate at [Event], [Date].')],
    ['<b>Player name</b> — the award belongs to them.',
     '<b>The specific award</b> — MVP, champion, most improved.',
     '<b>Team + season</b> — anchors it in time.',
     '<b>Coach signature</b> — personal and authentic.'],
    'What to Include',
    'If You Are the Coach',
    ['<b>One certificate per player</b> — MVP, most improved and participation cover a whole team.',
     '<b>Name the season</b> — “2026 Fall League” makes it a collectible.',
     '<b>Sign each one</b> — a coach\'s signature means more than a logo.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I add a team logo?','Yes — upload it.'),
     ('Can I print many?','Yes — one per player, seconds each.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Sports Award Certificate Now.',
    'Free to try — no signup.'),

  build('training-certificate-template.html',
    'Training Certificate Template + Wording (Free)',
    'Training certificate template with wording for workshops and seminars: hours, level, trainer. Edit and print free in your browser.',
    'Training Certificate Template',
    'A certificate that proves attendance and adds credibility to your training.',
    'Copy-Paste Training Wording',
    [('Standard', 'This certifies that [Name] completed the [Training] on [Date].'),
     ('With hours', 'For completing [Training], a [6]-hour program, and passing the assessment.'),
     ('Workshop', 'For joining [Hours] hours of hands-on learning in the [Workshop] workshop.'),
     ('Formal', 'This is to certify that [Name] has fulfilled the requirements of [Training] and is awarded this certificate.'),
     ('Short', 'For successful completion of [Training], [Date].')],
    ['<b>Participant name</b> — their credential.',
     '<b>Training title</b> — “Data Privacy Workshop”.',
     '<b>Duration or hours</b> — adds credibility.',
     '<b>Trainer + date</b> — who and when.'],
    'What to Include',
    'For Trainers & HR',
    ['<b>Hours and level make it resume-worthy</b> — a credential people can actually show.',
     '<b>Batch them</b> — one template, one name change, ~30 seconds each.',
     '<b>Your branding</b> — a logo turns a generic PDF into a branded credential.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I add my company logo?','Yes — upload it.'),
     ('Can I batch them?','Each takes ~30 seconds.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Training Certificate Now.',
    'Free to try — no signup.'),

  build('volunteer-certificate-template.html',
    'Volunteer Certificate Template + Wording (Free)',
    'Volunteer certificate template with wording that documents service: hours, organization, impact. Edit and print free in your browser.',
    'Volunteer Certificate',
    'A certificate that makes volunteer hours a documented, shareable record.',
    'Copy-Paste Volunteer Wording',
    [('Standard', 'With sincere gratitude to [Name] for [120] hours of volunteer service to [Organization].'),
     ('Impact', 'In recognition of [Name]\'s contribution to [Project], which reached [result].'),
     ('Organization', 'Presented by [Organization] in appreciation of [Name]\'s dedicated service in [Year].'),
     ('Warm', 'For showing up again and again and making [Organization] better every time.'),
     ('Formal', 'For outstanding volunteer service and commitment to [Cause] during [Period].')],
    ['<b>Volunteer name</b> — personal recognition.',
     '<b>The service</b> — hours, project, impact.',
     '<b>The organization</b> — who is grateful.',
     '<b>Date + signature</b> — official and warm.'],
    'What to Include',
    'Why It Matters',
    ['<b>Volunteers use these on resumes</b> — hours and organization make it a real record.',
     '<b>Name the impact</b> — “reached 300 families” beats “helped out”.',
     '<b>Warm design</b> — gratitude should look like gratitude, not a contract.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I list hours?','Yes — include them in the text.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Volunteer Certificate Now.',
    'Free to try — no signup.'),

  build('student-of-the-month-certificate.html',
    'Student of the Month Certificate + Wording (Free)',
    'Student of the month certificate template with wording for teachers: name the month, the behavior, the class. Edit and print free.',
    'Student of the Month Certificate',
    'Wording that rewards effort and behavior — not just grades.',
    'Copy-Paste Student of the Month Wording',
    [('Standard', 'Presented to [Name] as Student of the Month for [Month Year].'),
     ('Behavior', 'For kindness, effort and a positive attitude in [Class] during [Month].'),
     ('Effort', 'For consistent hard work and improvement in [Subject] during [Month].'),
     ('Classroom', 'Awarded by [Teacher]\'s class to [Name] for being a great classmate and leader.'),
     ('Warm', 'For showing up with a great attitude every single day this month.')],
    ['<b>Student name</b> — the star.',
     '<b>Month + reason</b> — behavior, effort or achievement.',
     '<b>Class or grade</b> — context.',
     '<b>Teacher signature</b> — personal.'],
    'What to Include',
    'Make It Motivate',
    ['<b>Reward behavior, not just grades</b> — kindness and effort motivate more students.',
     '<b>Name the month</b> — a dated series becomes a goal students aim for.',
     '<b>Send it home</b> — parents are the real audience for the certificate\'s impact.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Student of the Month Certificate Now.',
    'Free to try — no signup.'),

  build('printable-certificate-templates.html',
    'Printable Certificate Templates — Full Library + Wording',
    'Free printable certificate templates: completion, award, recognition and more, each with ready-to-copy wording. Edit in your browser, print on card stock.',
    'Printable Certificate Templates',
    'A full library — every template with its wording, ready to edit and print.',
    'Wording for the Most Common Templates',
    [('Completion', 'This certifies that [Name] has successfully completed [Program] on [Date].'),
     ('Award', 'Presented to [Name] in recognition of [achievement], [Date].'),
     ('Recognition', 'For outstanding contribution to [Team] during [Period].'),
     ('Appreciation', 'With sincere gratitude to [Name] for [contribution].'),
     ('Participation', 'For participating in [Event] on [Date].'),
     ('Achievement', 'Awarded to [Name] in recognition of exceptional effort and achievement in [Program].')],
    ['<b>Header line</b> — “This certifies that” (formal) vs “Presented to” (award).',
     '<b>Recipient</b> — full name, prominent.',
     '<b>Reason</b> — 2–4 sentences, specific.',
     '<b>Date + signatory</b> — authenticity.'],
    'What Every Certificate Needs',
    'Print Like a Pro',
    ['<b>Card stock (250gsm+)</b> — feels premium.',
     '<b>Borderless printing</b> if the design is full-bleed.',
     '<b>Check the PNG preview</b> — it shows exactly what prints.',
     '<b>Keep a digital copy</b> — the PNG is also great for email and LinkedIn.'],
    [('Are these templates free?','Yes — the free template is free; premium unlocks all for a one-time $9.99.'),
     ('Can I edit them?','Yes — every field and color is editable.'),
     ('What format do I get?','A print-ready PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Browse the Templates Now.',
    'Free to try — no signup, nothing uploaded.'),

  build('how-to-make-a-certificate-online.html',
    'How to Make a Certificate Online — Wording + 4-Step Guide',
    'How to make a certificate online free: pick a template, write the wording, add the details, print. Ready-to-copy phrasing included. Nothing uploaded.',
    'How to Make a Certificate Online',
    'The wording, the steps and the details — everything to make one now.',
    'Wording You Can Start From',
    [('Completion', 'This certifies that [Name] has successfully completed [Program] on [Date].'),
     ('Award', 'Presented to [Name] in recognition of [achievement], [Date].'),
     ('Recognition', 'For outstanding contribution to [Team] during [Period].'),
     ('Appreciation', 'With sincere gratitude to [Name] for [contribution].'),
     ('Participation', 'For participating in [Event] on [Date].')],
    ['<b>Recipient name</b> — the one thing everyone checks.',
     '<b>The reason</b> — specific, 2–4 sentences.',
     '<b>Date + organization</b> — who and when.',
     '<b>Signature</b> — adds weight.'],
    'What You Need to Fill In',
    'The 4 Steps',
    ['<b>1. Pick a template</b> — completion, award, recognition, participation and more.',
     '<b>2. Paste the wording</b> — use one of the examples above, fill in the blanks.',
     '<b>3. Add name, date, organization</b> — and a logo if you have one.',
     '<b>4. Download and print</b> — a high-res PNG, on card stock for the real thing.'],
    [('Is making certificates free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Do I need design software?','No — everything runs in your browser.'),
     ('Can I print it?','Yes — download a high-res PNG.'),
     ('Is my data uploaded?','No — everything is generated locally.')],
    'Make a Certificate Now.',
    'Free to try — no signup, nothing uploaded.'),

  build('birthday-invitation-maker.html',
    'Birthday Invitation Maker — Free Party Invitation Cards',
    'Make a birthday invitation card free: kids and adult party invites with the exact wording. Edit in your browser, download a print-ready PNG. Nothing uploaded.',
    'Birthday Invitation Maker',
    'Party invitations with wording that gets an RSVP — in your browser.',
    'Copy-Paste Birthday Invitation Wording',
    [('Kids party', 'You\'re invited to [Name]\'s [Age] birthday party! [Date] at [Time], [Location].'),
     ('Adult party', 'Join us to celebrate [Name]\'s birthday on [Date] at [Time]. Drinks, friends and cake.'),
     ('Surprise party', 'Shh — help us surprise [Name]! Join us on [Date] at [Time] at [Location].'),
     ('Short', 'Celebrate [Name]\'s birthday with us — [Date], [Time], [Location].'),
     ('Formal', 'You are cordially invited to celebrate the birthday of [Name] on [Date] at [Time].')],
    ['<b>Who\'s party</b> — name and age if it\'s a kids\' party.',
     '<b>Date, time, location</b> — the three things guests need.',
     '<b>RSVP line</b> — a phone or email makes it real.',
     '<b>Theme words</b> — “superhero”, “unicorn”, “garden party” set the mood.'],
    'What an Invitation Needs',
    'Make It Get an RSVP',
    ['<b>Date first</b> — the most-skipped detail; make it bold.',
     '<b>One theme color</b> — matches the party, keeps the card clean.',
     '<b>Include RSVP contact</b> — cards without it get zero responses.'],
    [('Is it free?','Yes — your first card is free; unlimited is a one-time $9.99.'),
     ('Can I edit the wording?','Yes — every field is editable.'),
     ('Can I print it?','Yes — download a high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Birthday Invitation Now.',
    'Free to try — no signup.',
    steps=['Open <a href="{base}/invitation-card-maker.html" style="color:#2c6ab3;font-weight:bold;">Invitation Card Maker</a>.',
           'Type the event title, message, date, time and location.',
           'Paste one of the wordings above into the message.',
           'Download a print-ready PNG.'], tool='invitation-card-maker.html', tool_name='Invitation Card Maker'),

  build('wedding-invitation-card-maker.html',
    'Wedding Invitation Card Maker — Free Elegant Invites',
    'Make a wedding invitation card free: elegant invites with formal wording. Edit in your browser, download a print-ready PNG. Nothing uploaded.',
    'Wedding Invitation Card Maker',
    'Elegant wedding invites with wording that sets the tone — in your browser.',
    'Copy-Paste Wedding Invitation Wording',
    [('Classic', 'Together with their families, [Name] and [Name] invite you to celebrate their marriage on [Date] at [Time], [Location].'),
     ('Formal', 'The honour of your presence is requested at the marriage of [Name] and [Name] on [Date].'),
     ('Modern', 'We\'re getting married! Join [Name] and [Name] on [Date] at [Time], [Location].'),
     ('Short', 'Save the date — [Name] & [Name], [Date], [Location]. Details to follow.'),
     ('Warm', 'Love is in the air — and you\'re invited. [Name] & [Name], [Date], [Time].')],
    ['<b>Names</b> — the couple, prominent and elegant.',
     '<b>Date, time, venue</b> — the essentials.',
     '<b>Ceremony vs reception</b> — one or both, with times.',
     '<b>RSVP details</b> — by date, via email or website.'],
    'What an Invitation Needs',
    'Make It Feel Elegant',
    ['<b>Formal wording</b> — “the honour of your presence” reads as a wedding.',
     '<b>Soft palette</b> — cream, blush or navy reads elegant; neon doesn\'t.',
     '<b>Serif typography</b> — a classic serif instantly says “wedding”.'],
    [('Is it free?','Yes — your first card is free; unlimited is a one-time $9.99.'),
     ('Can I edit the wording?','Yes — every field is editable.'),
     ('Can I print it?','Yes — download a high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Wedding Invitation Now.',
    'Free to try — no signup.',
    steps=['Open <a href="{base}/invitation-card-maker.html" style="color:#2c6ab3;font-weight:bold;">Invitation Card Maker</a>.',
           'Type the names, message, date, time and venue.',
           'Paste one of the wordings above into the message.',
           'Download a print-ready PNG.'], tool='invitation-card-maker.html', tool_name='Invitation Card Maker'),

  build('business-card-maker-online.html',
    'Business Card Maker Online — Free Professional Cards',
    'Make a business card online free: name, title, company and contact. Edit in your browser, download a print-ready PNG. Nothing uploaded.',
    'Business Card Maker Online',
    'A clean, professional card in 30 seconds — no design skills needed.',
    'What a Great Card Includes',
    [('Name + title', 'Your name and role — the two things people need to remember you by.'),
     ('Company', 'Your brand, with a logo or a clean wordmark.'),
     ('Contact', 'Phone, email and website — three lines, not a wall of text.'),
     ('Accent', 'One accent color ties the design together and makes it scannable.')],
    ['<b>Name</b> — the biggest text on the card.',
     '<b>Title + company</b> — the second line.',
     '<b>Phone / email / website</b> — keep to three lines.',
     '<b>One accent color</b> — matches your brand and stays professional.'],
    'What to Put on a Business Card',
    'Card Design Tips',
    ['<b>Bigger name, smaller details</b> — hierarchy makes cards scannable.',
     '<b>One accent color</b> — a clean card beats a busy one.',
     '<b>Standard size</b> — print at 3.5"×2" (or keep the ratio) for card wallets.'],
    [('Is it free?','Yes — your first card is free; unlimited is a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — download a high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Business Card Now.',
    'Free to try — no signup.',
    steps=['Open <a href="{base}/business-card-maker.html" style="color:#2c6ab3;font-weight:bold;">Business Card Maker</a>.',
           'Type name, title, company and contact.',
           'Pick your accent color.',
           'Download a print-ready PNG.'], tool='business-card-maker.html', tool_name='Business Card Maker'),

  build('name-tag-maker-online.html',
    'Name Tag Maker — Free Event & Conference Badges',
    'Make name tags free: conferences, meetings, classrooms. Edit a badge in your browser, download a print-ready PNG. Nothing uploaded.',
    'Name Tag Maker',
    'Clean event badges in 30 seconds — name, role and organization.',
    'What a Great Badge Includes',
    [('Name', 'Big and readable from across the room — the whole point.'),
     ('Role', 'Title or department, smaller than the name.'),
     ('Organization', 'Company or event, so people know the context.'),
     ('Accent', 'One brand color makes the badge feel designed.')],
    ['<b>Name</b> — the dominant element, readable at 2 meters.',
     '<b>Role + organization</b> — the second line.',
     '<b>Accent band</b> — a colored top bar or frame.',
     '<b>Clean layout</b> — a badge is scanned in a second.'],
    'What to Put on a Name Tag',
    'Badge Design Tips',
    ['<b>Name first, biggest</b> — people scan badges from across the room.',
     '<b>One accent color</b> — matches your event branding.',
     '<b>Standard lanyard size</b> — keep the badge to credit-card-ish proportions.'],
    [('Is it free?','Yes — your first tag is free; unlimited is a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — download a high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Name Tag Now.',
    'Free to try — no signup.',
    steps=['Open <a href="{base}/name-tag-maker.html" style="color:#2c6ab3;font-weight:bold;">Name Tag Maker</a>.',
           'Type name, role and organization.',
           'Pick your accent color.',
           'Download a print-ready PNG.'], tool='name-tag-maker.html', tool_name='Name Tag Maker'),

  build('diploma-maker-online.html',
    'Diploma Maker — Free Formal Diploma Generator',
    'Make a formal diploma free: recipient, degree, institution and date. Elegant serif design with a seal. Edit and print in your browser.',
    'Diploma Maker',
    'A formal diploma with a seal — in your browser, in 30 seconds.',
    'What a Diploma Includes',
    [('Recipient', 'The graduate\'s name, prominent and elegant.'),
     ('Degree / program', 'What they earned — “Bachelor of Science”.'),
     ('Institution', 'The authority behind the credential.'),
     ('Date + seal', 'The milestone and the mark of authenticity.')],
    ['<b>Recipient</b> — the largest text, formal serif.',
     '<b>Program + institution</b> — the credential and who issued it.',
     '<b>Seal or emblem</b> — a small seal makes it feel official.',
     '<b>Signature line</b> — “Registrar” or the issuer\'s name.'],
    'What to Put on a Diploma',
    'Diploma Design Tips',
    ['<b>Formal serif</b> — Georgia-style typography says “diploma”.',
     '<b>A seal</b> — a small emblem or medallion adds authenticity.',
     '<b>Borders</b> — a double border frames the formality.'],
    [('Is it free?','Yes — your first diploma is free; unlimited is a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — download a high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Diploma Now.',
    'Free to try — no signup.',
    steps=['Open <a href="{base}/diploma-maker.html" style="color:#2c6ab3;font-weight:bold;">Diploma Maker</a>.',
           'Type recipient, program, institution and date.',
           'Pick your accent color.',
           'Download a print-ready PNG.'], tool='diploma-maker.html', tool_name='Diploma Maker'),

  build('retirement-certificate-template.html',
    'Retirement Certificate Template + Funny & Formal Wording (Free)',
    'Retirement certificate template with funny and formal wording to copy: years of service, farewell, well-wishes. Edit in your browser, print and present. Free.',
    'Retirement Certificate Template',
    'A farewell that reads like a celebration — funny for the party, formal for the plaque.',
    'Copy-Paste Retirement Wording',
    [('Funny', 'This certifies that [Name] has officially completed [30] years of professional service — and is hereby licensed to enjoy the good life.'),
     ('Formal', 'In recognition of [Name]\'s [30] years of dedicated service to [Company], presented with gratitude on [Date].'),
     ('Sentimental', 'After [30] years, [Name] isn\'t retiring from the team — they\'re graduating to full-time family, coffee and well-earned rest.'),
     ('Milestone', 'Presented to [Name] for [30] years of outstanding contribution, on the occasion of their retirement, [Date].'),
     ('Short', 'Retired with honor and affection, [Date].')],
    ['<b>Name</b> — the guest of honor.',
     '<b>Years of service</b> — count them; it\'s the whole point.',
     '<b>Company / department</b> — the institution they served.',
     '<b>Signature + date</b> — the person and the day.'],
    'What to Put on a Retirement Certificate',
    'Funny or Formal?',
    ['<b>Read the room</b> — a humorous plaque lands at the party; a formal one gets framed in the office.',
     '<b>Count the years</b> — "30 years" is the detail people brag about.',
     '<b>Sign it</b> — a personalized signature beats a printed logo.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit the wording?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG, card stock recommended.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Retirement Certificate Now.',
    'Free to try — no signup, nothing uploaded.'),

  build('gift-certificate-template.html',
    'Gift Certificate Template — Make a Voucher in Minutes (Free)',
    'Gift certificate template for any business: amount, recipient, expiry, code. Edit in your browser and print a polished voucher. Free, nothing uploaded.',
    'Gift Certificate Template',
    'A gift card you can make in 30 seconds — no design skills, no uploads.',
    'Gift Certificate Wording',
    [('Standard', 'This certificate entitles [Name] to [Amount] toward goods and services at [Business].'),
     ('Experience', 'A gift of [Massage / Dinner / Tickets] from [Giver] to [Name] — enjoy!'),
     ('Service', 'Presented to [Name] as a gift of [Amount] to be used at [Business].'),
     ('Short', 'Gift certificate: [Amount] — good toward any [Product/Service].'),
     ('Custom', 'For [Name], with love — worth [Amount] at [Business].')],
    ['<b>Recipient name</b> — the person who will spend it.',
     '<b>Amount or value</b> — the most important number, prominent.',
     '<b>Expiry</b> — a date keeps it honest and creates urgency.',
     '<b>Issuer + a code</b> — your business name and a unique number for tracking.'],
    'What a Gift Certificate Needs',
    'Make It Look Legit',
    ['<b>Amount big, terms small</b> — the value is the hero.',
     '<b>Add an expiry date</b> — expiring gift cards get spent.',
     '<b>Include a code</b> — a simple unique number lets you track redemptions.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I add my business name?','Yes — all text and colors are editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Gift Certificate Now.',
    'Free to try — no signup, nothing uploaded.'),

  build('first-place-certificate.html',
    '1st Place Certificate Template + Winner Wording (Free)',
    '1st place certificate template with winner wording: champions, category winners, team first place. Edit and print free in your browser.',
    '1st Place Certificate',
    'The certificate that names the winner — and the exact reason they earned it.',
    'Copy-Paste First Place Wording',
    [('1st place', 'This certificate is proudly presented to [Name] for taking 1st place at the [Event] on [Date].'),
     ('Champion', 'Awarded to [Name] as the champion of [Tournament/Competition], [Date].'),
     ('Category winner', 'For first place in the [Category] division at [Event], [Date].'),
     ('Team', 'Presented to [Team Name] for finishing 1st in the [League/Division] [Season].'),
     ('Short', '1st place — [Event], [Date].')],
    ['<b>Winner name</b> — big and centered.',
     '<b>The event + date</b> — what and when.',
     '<b>Category or division</b> — for multi-category events.',
     '<b>Signer</b> — the organizer or coach.'],
    'What to Put on It',
    'Make It Frameworthy',
    ['<b>Name the category</b> — "U12 girls division" means more than "1st place".',
     '<b>Date it</b> — a dated win is a collectible.',
     '<b>Bold border</b> — a strong frame says "winner".'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a First Place Certificate Now.',
    'Free to try — no signup.'),

  build('perfect-attendance-certificate.html',
    'Perfect Attendance Certificate Template + Wording (Free)',
    'Perfect attendance certificate template for schools and offices: name the period, reward the consistency. Edit and print free in your browser.',
    'Perfect Attendance Certificate',
    'Reward the achievement everyone respects: showing up, every day.',
    'Copy-Paste Attendance Wording',
    [('Standard', 'Presented to [Name] for perfect attendance during [Period].'),
     ('School', 'This certifies that [Name] attended [School] with no absences during [Term].'),
     ('Employee', 'Awarded to [Name] for perfect attendance at [Company] during [Period].'),
     ('Warm', 'For showing up with a smile, every single day, for [Period].'),
     ('Short', 'Perfect attendance — [Period].')],
    ['<b>Name</b> — the achiever.',
     '<b>The period</b> — month, term or year.',
     '<b>School / company</b> — the institution.',
     '<b>Signature</b> — principal, teacher or manager.'],
    'What to Include',
    'Make It Motivate',
    ['<b>Name the period</b> — "Fall 2026" makes it a real record.',
     '<b>Reward consistency</b> — attendance awards encourage the quiet achievers.',
     '<b>Print a stack</b> — one per student, seconds each.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Perfect Attendance Certificate Now.',
    'Free to try — no signup.'),

  build('honor-roll-certificate.html',
    'Honor Roll Certificate Template + Wording (Free)',
    'Honor roll certificate template with wording for principals and teachers: GPA, semester, students. Edit and print free in your browser.',
    'Honor Roll Certificate',
    'A certificate that makes academic achievement official.',
    'Copy-Paste Honor Roll Wording',
    [('Standard', 'Presented to [Name] for making the Honor Roll during [Semester].'),
     ('With GPA', 'For achieving a [3.5] GPA and a place on the Honor Roll for [Term].'),
     ('Principal\'s list', 'Awarded to [Name] for outstanding academic achievement and a place on the Principal\'s List, [Term].'),
     ('Semester', 'For maintaining excellent grades throughout the [Fall] semester, [Year].'),
     ('Warm', 'For dedication, focus and a place on the Honor Roll — keep going, [Name]!')],
    ['<b>Student name</b> — the academic star.',
     '<b>The term</b> — semester or year.',
     '<b>GPA if used</b> — only if your school reports it.',
     '<b>Principal / teacher signature</b> — authority.'],
    'What to Include',
    'For Principals & Teachers',
    ['<b>Name the term</b> — a dated honor roll becomes a series students chase.',
     '<b>Match your policy</b> — GPA thresholds differ; keep the wording generic unless you list one.',
     '<b>Print on card stock</b> — these go on refrigerators.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make an Honor Roll Certificate Now.',
    'Free to try — no signup.'),

  build('reading-award-certificate.html',
    'Reading Award Certificate + Bookworm Wording (Free)',
    'Reading award certificate with wording for summer reading and classroom challenges: books read, milestones. Edit and print free in your browser.',
    'Reading Award Certificate',
    'Reward the readers — the habit that pays back forever.',
    'Copy-Paste Reading Award Wording',
    [('Bookworm', 'Presented to [Name], official Bookworm, for reading [20] books in [Period].'),
     ('Reading challenge', 'Awarded to [Name] for completing the [Summer] Reading Challenge, [Date].'),
     ('Most books read', 'For reading more books than anyone else in [Class] this [Term].'),
     ('Milestone', 'For reaching [100] books in [Grade]. A true champion reader!'),
     ('Warm', 'For loving stories and turning pages — keep reading, [Name]!')],
    ['<b>Reader name</b> — the star.',
     '<b>The achievement</b> — number of books or the challenge.',
     '<b>The period</b> — summer, term or year.',
     '<b>Teacher / librarian signature</b> — personal.'],
    'What to Include',
    'Make Reading Fun',
    ['<b>Numbers motivate</b> — "20 books" is a number kids love to beat.',
     '<b>Run it as a challenge</b> — summer reading programs get more readers.',
     '<b>One per reader</b> — everyone who finishes gets one.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Reading Award Now.',
    'Free to try — no signup.'),

  build('preschool-graduation-certificate.html',
    'Preschool Graduation Certificate Template + Cute Wording (Free)',
    'Preschool graduation certificate with sweet wording for little graduates: moving up, big kid, completion. Edit and print free in your browser.',
    'Preschool Graduation Certificate',
    'A certificate so cute it ends up on the fridge for years.',
    'Copy-Paste Preschool Wording',
    [('Moving up', 'This certifies that [Name] has successfully graduated from Preschool and is officially moving up to [Kindergarten]!'),
     ('Sweet', 'Presented to [Name] for growing, learning and being awesome in [Class], [Year].'),
     ('Big kid', '[Name] has completed [School]\'s preschool program and is now a big kid — congratulations!'),
     ('Tiny graduate', 'Officially certified: [Name] is ready for the big world of [Grade].'),
     ('Warm', 'For every song, every story and every "I did it!" — congratulations, [Name]!')],
    ['<b>Graduate name</b> — the whole point.',
     '<b>The program</b> — preschool, Pre-K, nursery.',
     '<b>School + year</b> — context.',
     '<b>Teacher signature</b> — a name the kid recognizes.'],
    'What to Include',
    'Make It a Keepsake',
    ['<b>Big, friendly fonts</b> — the kid should be able to read their own name.',
     '<b>Leave room for a photo</b> — a small photo makes it a real keepsake.',
     '<b>Warm colors</b> — pastels read "preschool", not "boardroom".'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Preschool Graduation Certificate Now.',
    'Free to try — no signup.'),

  build('homeschool-completion-certificate.html',
    'Homeschool Completion Certificate Template (Free)',
    'Homeschool completion certificate template for grade levels and subjects: parent-issued credentials that look official. Edit and print free.',
    'Homeschool Completion Certificate',
    'A parent-issued certificate that still looks official enough to frame.',
    'Copy-Paste Homeschool Wording',
    [('Grade completion', 'This certifies that [Name] has successfully completed [Grade] at [Homeschool], [Year].'),
     ('Subject completion', 'For completing [Subject/Curriculum] with distinction, [Year].'),
     ('Formal', 'This is to certify that [Name] has fulfilled the requirements of [Grade] and is promoted to [Next Grade].'),
     ('Portfolio', 'Presented to [Name] for completing [Program] with a full portfolio of work, [Year].'),
     ('Warm', 'Congratulations, [Name] — another year of learning, curiosity and growth!')],
    ['<b>Student name</b> — the graduate.',
     '<b>Grade or subject</b> — what was completed.',
     '<b>The year</b> — an official feel.',
     '<b>Parent / teacher signature</b> — the authority.'],
    'What to Include',
    'Why Keep These',
    ['<b>Portfolios need proof</b> — certificates document what you covered.',
     '<b>Name the curriculum</b> — "Singapore Math" or "Apologia" adds credibility.',
     '<b>Print one per subject</b> — a stack looks like a real transcript.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Homeschool Certificate Now.',
    'Free to try — no signup.'),

  build('best-mom-certificate.html',
    'Best Mom Certificate — Funny Mother\'s Day Award (Free)',
    'Best mom certificate with funny and heartfelt wording: from kids, for Mother\'s Day or any day. Edit and print free in your browser.',
    'Best Mom Certificate',
    'A framed "official" declaration that mom is the best. By unanimous vote.',
    'Copy-Paste Best Mom Wording',
    [('Funny', 'This certifies that [Mom\'s Name] is the official, world-class, 100% certified Best Mom. No contest was held because there was no competition.'),
     ('From the kids', 'Presented by [Kids] to the Best Mom in the universe, [Mom\'s Name], for unlimited snacks and unconditional love.'),
     ('Mother\'s Day', 'For surviving [X] years of [Family] chaos with grace, humor and snacks — Happy Mother\'s Day!'),
     ('Heartfelt', 'For every bandage, every late night, every "try again" — thank you, mom.'),
     ('Short', 'World\'s Best Mom — officially, [Date].')],
    ['<b>Mom\'s name</b> — the honoree.',
     '<b>From whom</b> — the kids, by name.',
     '<b>The "reason"</b> — funny beats formal here.',
     '<b>Date</b> — makes it a keepsake.'],
    'What to Include',
    'Make It Land',
    ['<b>Funny wins</b> — a joke mom will repeat beats corporate phrasing.',
     '<b>Sign it as a family</b> — names of the kids make it priceless.',
     '<b>Print and frame</b> — this belongs on the wall, not in a drawer.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Best Mom Certificate Now.',
    'Free to try — no signup.'),

  build('best-dad-certificate.html',
    'Best Dad Certificate — Funny Father\'s Day Award (Free)',
    'Best dad certificate with funny and heartfelt wording: from kids, for Father\'s Day or any day. Edit and print free in your browser.',
    'Best Dad Certificate',
    'An "official" certificate dad will brag about for years.',
    'Copy-Paste Best Dad Wording',
    [('Funny', 'This certifies that [Dad\'s Name] is the official Best Dad, a title earned through years of dad jokes, grilling and questionable advice.'),
     ('From the kids', 'Presented by [Kids] to [Dad\'s Name], Best Dad ever, for fixing everything and pretending to listen.'),
     ('Father\'s Day', 'For teaching, protecting and providing [X] years of excellent dad energy — Happy Father\'s Day!'),
     ('Heartfelt', 'For every drive, every lesson, every "watch this" — thank you, dad.'),
     ('Short', 'World\'s Best Dad — officially, [Date].')],
    ['<b>Dad\'s name</b> — the honoree.',
     '<b>From whom</b> — the kids, by name.',
     '<b>The "reason"</b> — make it personal.',
     '<b>Date</b> — a keepsake.'],
    'What to Include',
    'Make It Land',
    ['<b>Dad humor</b> — lean into the dad jokes.',
     '<b>Personal details</b> — one specific memory beats a generic line.',
     '<b>Print it</b> — a framed "official" certificate is peak dad decoration.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Best Dad Certificate Now.',
    'Free to try — no signup.'),

  build('music-recital-certificate.html',
    'Music Recital Certificate + Award Wording (Free)',
    'Music recital certificate with wording for piano, violin and band recitals: participation, outstanding performance. Edit and print free in your browser.',
    'Music Recital Certificate',
    'A certificate that makes a recital feel like a real performance — because it is.',
    'Copy-Paste Recital Wording',
    [('Recital participation', 'This certificate is presented to [Name] for performing at the [Studio] Recital on [Date].'),
     ('Outstanding performance', 'For a beautiful performance of [Piece] at the [Season] Recital.'),
     ('Piano recital', 'Awarded to [Name] for completing the [Piano] recital program with confidence and skill, [Date].'),
     ('Achievement', 'For [Hours] of practice and a memorable performance at [Event], [Date].'),
     ('Warm', 'For sharing your music with all of us — we\'re so proud of you, [Name]!')],
    ['<b>Performer name</b> — the star of the show.',
     '<b>The piece</b> — name the song or movement.',
     '<b>Event + date</b> — which recital.',
     '<b>Teacher signature</b> — the person who taught them.'],
    'What to Include',
    'For Music Teachers',
    ['<b>Name the piece</b> — "Sonatina in G" is a detail kids will remember.',
     '<b>One per student</b> — every performer earns one.',
     '<b>Print on card stock</b> — these get pinned to music stands.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Music Recital Certificate Now.',
    'Free to try — no signup.'),

  build('choir-award-certificate.html',
    'Choir Award Certificate + Wording (Free)',
    'Choir award certificate with wording for outstanding vocalists, choral achievement and concerts. Edit and print free in your browser.',
    'Choir Award Certificate',
    'Recognize the voices that carry the whole choir.',
    'Copy-Paste Choir Wording',
    [('Outstanding vocalist', 'Presented to [Name] for outstanding vocal performance in the [Choir] this [Season].'),
     ('Choral achievement', 'In recognition of [Name]\'s dedication and musicianship in the [Concert], [Date].'),
     ('Participation', 'For lending your voice to the [Concert] with [Choir], [Date].'),
     ('Section award', 'Awarded to [Name], outstanding [Soprano/Alto/Tenor/Bass], for the [Season] concert season.'),
     ('Warm', 'For singing your heart out and making [Choir] better — thank you, [Name]!')],
    ['<b>Singer name</b> — the honoree.',
     '<b>The achievement</b> — vocalist, participation, section.',
     '<b>Concert / season</b> — context.',
     '<b>Director signature</b> — personal.'],
    'What to Include',
    'For Choir Directors',
    ['<b>One award per role</b> — vocalist, section leader and participation cover a choir.',
     '<b>Name the concert</b> — "Spring Concert 2026" is a collectible.',
     '<b>Sign each one</b> — a director\'s signature means more than a logo.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Choir Award Now.',
    'Free to try — no signup.'),

  build('first-aid-certificate.html',
    'First Aid & CPR Certificate Template (Free)',
    'First aid and CPR certificate template for training centers: course, instructor, valid-until date. Edit and print free in your browser.',
    'First Aid & CPR Certificate',
    'A credential look that matches the training — clean, official, dated.',
    'Copy-Paste First Aid Wording',
    [('Standard', 'This certifies that [Name] has successfully completed [First Aid/CPR] training on [Date].'),
     ('With validity', 'This certifies that [Name] completed [CPR/AED] training, valid through [Date].'),
     ('Course', 'For completing the [Heartsaver / Standard First Aid] course with [Instructor].'),
     ('Formal', 'This is to certify that [Name] has fulfilled the requirements of [Course] and is awarded this certificate.'),
     ('Short', 'Successfully completed [Course], [Date].')],
    ['<b>Participant name</b> — their credential.',
     '<b>The course</b> — First Aid, CPR, AED, or combined.',
     '<b>Valid-until date</b> — where your program requires renewal.',
     '<b>Instructor + date</b> — who and when.'],
    'What to Include',
    'For Training Centers',
    ['<b>Validity dates matter</b> — many credentials renew; a clear date avoids confusion.',
     '<b>Instructor signature</b> — the person who verified.',
     '<b>Keep it clean</b> — a credential should look calm and official.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a First Aid Certificate Now.',
    'Free to try — no signup.'),

  build('potty-training-certificate.html',
    'Potty Training Certificate — Funny & Sweet (Free)',
    'Potty training certificate with funny and sweet wording for little graduates: big kid, no more diapers. Edit and print free in your browser.',
    'Potty Training Certificate',
    'The most important credential a toddler will ever earn.',
    'Copy-Paste Potty Training Wording',
    [('Funny', 'This certifies that [Name] has successfully completed Potty Training and is hereby promoted to Big Kid status. No diapers were harmed (much).'),
     ('Sweet', 'Presented to [Name] for mastering the big potty. We\'re so proud of you!'),
     ('Celebration', 'Official notice: [Name] is a Big Kid now. The diapers have been officially retired.'),
     ('From parents', 'Certified by [Parents] that [Name] passed Potty School with honors and a sense of style.'),
     ('Short', 'Big Kid status: achieved. Congratulations, [Name]!')],
    ['<b>Graduate name</b> — the hero.',
     '<b>A "reason"</b> — funny, sweet or both.',
     '<b>From whom</b> — parents or grandparents.',
     '<b>Date</b> — a date you\'ll tell at their wedding.'],
    'What to Include',
    'Make It a Memory',
    ['<b>Funny wins</b> — this is the certificate the family quotes for years.',
     '<b>Big, bold text</b> — the kid should see their name first.',
     '<b>Print two</b> — one to display, one for the baby book.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Potty Training Certificate Now.',
    'Free to try — no signup.'),

  build('kids-award-certificate.html',
    'Award Certificates for Kids — Templates + Wording (Free)',
    'Award certificates for kids with positive wording: super helper, kindest friend, math wizard, most improved. Edit and print free in your browser.',
    'Award Certificates for Kids',
    'Positive awards that celebrate behavior, effort and kindness — not just grades.',
    'Copy-Paste Kids Award Wording',
    [('Super helper', 'Presented to [Name] for always lending a hand. You make [Class] better!'),
     ('Kindest friend', 'For being a kind, caring friend to everyone in [Class], [Year].'),
     ('Math wizard', 'For amazing effort and skill in math — keep those numbers dancing, [Name]!'),
     ('Most improved', 'For the most improvement this term. We\'re so proud of you, [Name]!'),
     ('Brave', 'For showing courage, trying new things and never giving up.')],
    ['<b>Child name</b> — the star.',
     '<b>The award</b> — a positive trait, not just an achievement.',
     '<b>Class + year</b> — context.',
     '<b>Teacher signature</b> — personal.'],
    'What to Include',
    'Make Every Kid a Winner',
    ['<b>One award per child</b> — everyone should get something positive.',
     '<b>Behavior beats grades</b> — kindness and effort reach more kids.',
     '<b>Send it home</b> — parents are the real audience.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Kids Award Now.',
    'Free to try — no signup.'),

  build('service-award-certificate.html',
    'Service Award Certificate + Years of Service Wording (Free)',
    'Service award certificate with years-of-service wording for milestones: 5, 10, 25 years. Edit and print free in your browser.',
    'Service Award Certificate',
    'A milestone that says "we noticed, and we remember."',
    'Copy-Paste Service Award Wording',
    [('Years of service', 'Presented to [Name] in recognition of [10] years of dedicated service to [Company].'),
     ('Milestone', 'This certificate honors [Name]\'s [5] year anniversary with [Company], [Date].'),
     ('Corporate', 'For exemplary commitment and contribution to [Department] over [Years] years.'),
     ('Retirement bridge', 'In appreciation of [Name]\'s [25] years of service, presented on the occasion of their retirement.'),
     ('Warm', 'For [Years] years of showing up, building things and being part of the family.')],
    ['<b>Employee name</b> — the honoree.',
     '<b>Years of service</b> — the milestone.',
     '<b>Company + department</b> — context.',
     '<b>Signature + date</b> — official.'],
    'What to Include',
    'Make It a Milestone',
    ['<b>Count the years</b> — "10 years" is the headline.',
     '<b>Add the company logo</b> — makes it feel official.',
     '<b>Frame-worthy design</b> — service awards get hung on walls.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('Can I add a logo?','Yes — upload it in the editor.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Service Award Now.',
    'Free to try — no signup.'),

  build('baby-shower-invitation-maker.html',
    'Baby Shower Invitation Maker — Free Cute Cards',
    'Make a baby shower invitation free: it\'s a boy, it\'s a girl, co-ed. Cute wording included. Edit in your browser, print a PNG. Nothing uploaded.',
    'Baby Shower Invitation Maker',
    'Cute invites that set the tone for the party — no uploads, no signup.',
    'Copy-Paste Baby Shower Wording',
    [('Classic', 'You\'re invited to a baby shower for [Mom Name] on [Date] at [Time], [Location].'),
     ('It\'s a boy', 'A little man is on the way! Join us for a baby shower honoring [Mom Name], [Date].'),
     ('It\'s a girl', 'A tiny princess is coming! Help us shower [Mom Name], [Date] at [Location].'),
     ('Co-ed', 'Both parents-to-be — join [Names] for a co-ed baby shower on [Date], [Time].'),
     ('Short', 'Baby shower for [Mom Name] — [Date], [Time], [Location]. RSVP by [Date].')],
    ['<b>Mom-to-be\'s name</b> — the guest of honor.',
     '<b>Date, time, location</b> — the essentials.',
     '<b>Theme words</b> — "it\'s a boy/girl", "jungle", "stars" set the mood.',
     '<b>Registry or RSVP line</b> — make it easy.'],
    'What an Invitation Needs',
    'Make It Get an RSVP',
    ['<b>Date first</b> — make it bold.',
     '<b>One theme color</b> — matches the party, keeps the card clean.',
     '<b>Include RSVP contact</b> — cards without it get no responses.'],
    [('Is it free?','Yes — your first card is free; unlimited is a one-time $9.99.'),
     ('Can I edit the wording?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Baby Shower Invitation Now.',
    'Free to try — no signup.',
    steps=['Open <a href="{base}/invitation-card-maker.html" style="color:#2c6ab3;font-weight:bold;">Invitation Card Maker</a>.',
           'Type the event title, message, date, time and location.',
           'Paste one of the wordings above into the message.',
           'Download a print-ready PNG.'], tool='invitation-card-maker.html', tool_name='Invitation Card Maker'),

  build('raffle-ticket-maker.html',
    'Raffle Ticket Maker — Free Event & Fundraising Tickets',
    'Make raffle tickets free: event, prize, date, unique number. Edit in your browser and print a sheet of tickets. Nothing uploaded.',
    'Raffle Ticket Maker',
    'Fundraising tickets with a real number stub — in your browser, in a minute.',
    'What a Raffle Ticket Includes',
    [('Event', 'The fundraiser, school fair or charity event name — the reason people are buying.'),
     ('Prize', 'The prize worth showing up for — "$500 Gift Card".'),
     ('Number', 'The unique ticket number that makes a draw honest.'),
     ('Stub', 'A tear-off stub keeps the number for the draw.')],
    ['<b>Event name</b> — the context.',
     '<b>Prize</b> — the hook.',
     '<b>Ticket number</b> — unique and visible.',
     '<b>Date + price</b> — when and how much.'],
    'What to Put on a Raffle Ticket',
    'Raffle Design Tips',
    ['<b>Number big</b> — a legible number makes the draw smooth.',
     '<b>Prize front and center</b> — that\'s what sells the ticket.',
     '<b>Print on card stock</b> — a sturdy ticket feels like a real entry.'],
    [('Is it free?','Yes — your first ticket is free; unlimited is a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Raffle Ticket Now.',
    'Free to try — no signup.',
    steps=['Open <a href="{base}/event-ticket-maker.html" style="color:#2c6ab3;font-weight:bold;">Event Ticket Maker</a>.',
           'Type the event, prize, date and ticket details.',
           'Set your accent color and layout.',
           'Download a print-ready sheet.'], tool='event-ticket-maker.html', tool_name='Event Ticket Maker'),

  build('wedding-thank-you-card-maker.html',
    'Wedding Thank You Card Maker — Free Printable',
    'Make wedding thank you cards free: from the couple, elegant wording. Edit in your browser and print or share. Nothing uploaded.',
    'Wedding Thank You Card Maker',
    'A thank-you that matches the wedding — elegant, personal, quick.',
    'Copy-Paste Wedding Thank You Wording',
    [('Classic', 'Thank you for your generous gift and for celebrating our wedding. With love, [Names].'),
     ('Warm', 'We\'re so grateful you shared our day — and for your thoughtful gift. Love, [Names].'),
     ('From the couple', 'Thank you for your kindness and generosity as we start our life together. [Names].'),
     ('Short', 'Thank you for celebrating with us! Love, [Names].'),
     ('With a detail', 'Thank you for the [gift] — and for being part of the best day of our lives. [Names].')],
    ['<b>Names of the couple</b> — the sign-off.',
     '<b>A personal line</b> — mention the gift or a moment.',
     '<b>Stationery vibe</b> — elegant and clean.'],
    'What to Include',
    'Make It Feel Personal',
    ['<b>Mention the gift</b> — one specific line makes it feel handwritten.',
     '<b>Keep it short</b> — a thank-you doesn\'t need paragraphs.',
     '<b>Match the wedding style</b> — same palette as your invites.'],
    [('Is it free?','Yes — your first card is free; unlimited is a one-time $9.99.'),
     ('Can I edit the wording?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Wedding Thank You Card Now.',
    'Free to try — no signup.',
    steps=['Open <a href="{base}/thank-you-card-maker.html" style="color:#2c6ab3;font-weight:bold;">Thank You Card Maker</a>.',
           'Type the message and the couple\'s names.',
           'Pick a template and accent color.',
           'Download a print-ready PNG.'], tool='thank-you-card-maker.html', tool_name='Thank You Card Maker'),

  build('save-the-date-maker.html',
    'Save the Date Card Maker — Free Printable',
    'Make a save the date card free: names, date, location. Simple and elegant. Edit in your browser, print or share. Nothing uploaded.',
    'Save the Date Card Maker',
    'A clean save-the-date that gets the date into calendars early.',
    'Copy-Paste Save the Date Wording',
    [('Classic', 'Save the date — [Names] are getting married on [Date], [Location]. Invitation to follow.'),
     ('Short', 'Save the date: [Names], [Date]. Details to come.'),
     ('Formal', 'The honour of your company is requested at the marriage of [Names], [Date].'),
     ('Playful', 'We\'re tying the knot! Save the date — [Date], [Location].'),
     ('Minimal', '[Names] · [Date] · [Location]')],
    ['<b>Names</b> — who\'s getting married.',
     '<b>The date</b> — the whole point, prominent.',
     '<b>Location + city</b> — helps guests plan.',
     '<b>Hint at the vibe</b> — formal or playful.'],
    'What to Include',
    'Make It Work',
    ['<b>Date is the hero</b> — make it the biggest element.',
     '<b>Keep it minimal</b> — save-the-dates don\'t need full details.',
     '<b>Match the wedding palette</b> — a preview of the invitation style.'],
    [('Is it free?','Yes — your first card is free; unlimited is a one-time $9.99.'),
     ('Can I edit it?','Yes — every field is editable.'),
     ('Can I print it?','Yes — high-res PNG.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Save the Date Now.',
    'Free to try — no signup.',
    steps=['Open <a href="{base}/invitation-card-maker.html" style="color:#2c6ab3;font-weight:bold;">Invitation Card Maker</a>.',
           'Type the names, date and location.',
           'Pick a template and accent color.',
           'Download a print-ready PNG.'], tool='invitation-card-maker.html', tool_name='Invitation Card Maker'),

  build('teacher-award-certificate-template.html',
    'Teacher Award Certificate Template + Wording for Students (Free)',
    'Teacher award certificate template for classroom rewards. Ready-to-copy wording for achievement, effort and attendance awards — AI-friendly, edit and print free in your browser.',
    'Teacher Award Certificate Template for Students',
    'A template plus classroom-tested wording — give students an award that looks real in 30 seconds.',
    'Copy-Paste Classroom Award Wording',
    [('Achievement', 'Awarded to [Name] for outstanding achievement in [Subject] during [Term].'),
     ('Most improved', 'Presented to [Name] for the most improvement in [Subject] — [Specific progress].'),
     ('Perfect attendance', 'This certificate is proudly presented to [Name] for perfect attendance during [Term].'),
     ('Kindness & community', 'Awarded to [Name] for making our classroom a kinder place through [Specific behavior].'),
     ('Reading challenge', 'Presented to [Name] for completing the [Term] reading challenge with [N] books.'),
     ('Great effort', 'This certificate celebrates [Name] for consistent effort and a can-do attitude in [Subject].')],
    ['<b>Student name</b> — spelled exactly right, it\'s the part they keep.',
     '<b>The award</b> — achievement, effort, attendance: name the real thing.',
     '<b>Specific reason</b> — “improved 20% on math quizzes” beats “good job”.',
     '<b>Date + teacher signature</b> — both make it feel official.'],
    'What to Put on a Classroom Certificate',
    'Awards Students Actually Care About',
    ['<b>Name the result, not the trait</b> — “raised their reading level by two grades” lands harder than “great reader”.',
     '<b>Use one accent color</b> — a clean border in school colors reads real without clutter.',
     '<b>Batch them</b> — make a whole class set in one sitting and keep spares.'],
    [('Is it free?','Yes — the free template is free to use; premium unlocks for a one-time $9.99.'),
     ('Can I use AI to write award wording?','Yes — paste the wording above into any AI tool and ask it to personalize it for your student; the certificate itself still runs free in your browser.'),
     ('Can I print them?','Yes — download a high-res PNG, sized for 8.5×11.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Teacher Award Certificate Now.',
    'Free to try — no signup, nothing uploaded.'),

  build('classroom-certificates-for-students.html',
    'Classroom Certificates for Students: 12 Types + Free Wording',
    '12 classroom certificate ideas for students with ready-to-copy wording: achievement, attendance, kindness, reading, effort and more. Edit and print free in your browser.',
    'Classroom Certificates for Students: 12 Types',
    'Award cards that actually motivate — pick a type, copy the wording, print.',
    'Wording for 12 Certificate Types',
    [('Achievement', 'Awarded to [Name] for outstanding achievement in [Subject].'),
     ('Most improved', 'Presented to [Name] for the most improvement in [Subject] during [Term].'),
     ('Perfect attendance', 'Proudly presented to [Name] for perfect attendance in [Term].'),
     ('Kindness award', 'Awarded to [Name] for making our classroom kinder through [Behavior].'),
     ('Reading champion', 'Presented to [Name] for finishing [N] books in the [Term] reading challenge.'),
     ('STEM explorer', 'Awarded to [Name] for curiosity and problem-solving in [Science/Math/STEM].'),
     ('Great teammate', 'Presented to [Name] for lifting up classmates during [Project/Activity].'),
     ('Creative thinker', 'Awarded to [Name] for original thinking in [Subject/Project].')],
    ['<b>Student name</b> — large, centered, spelled right.',
     '<b>Type of award</b> — one specific thing, not a laundry list.',
     '<b>Reason line</b> — 1–2 sentences; name the result or behavior.',
     '<b>Date + signatory</b> — teacher name and date anchor it.'],
    'What Makes a Classroom Certificate Count',
    'Keep a Stack Ready',
    ['<b>Specific beats generic</b> — “finished the 100-book challenge” beats “good reader”.',
     '<b>Make spares</b> — pre-print a blank stack and fill names by hand for on-the-spot awards.',
     '<b>Match school colors</b> — one border color in school palette looks intentional.'],
    [('Is it free?','Yes — the free template is free; premium unlocks everything for a one-time $9.99.'),
     ('Can I use AI to personalize wording?','Yes — the phrasing above works as a prompt; ask AI to adapt it per student.'),
     ('How do I print?','Download the high-res PNG and print on letter paper.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make Classroom Certificates Now.',
    'Free to try — no signup.'),

  build('teacher-appreciation-week-certificate.html',
    'Teacher Appreciation Week Certificate + Wording (Free)',
    'Teacher Appreciation Week certificate with warm thank-you wording from students and parents. Edit and print free in your browser — nothing uploaded.',
    'Teacher Appreciation Certificate',
    'Tell a teacher they mattered — a certificate they will keep.',
    'Copy-Paste Thank-You Wording',
    [('From a student', 'Thank you, [Teacher Name], for making [Subject] something I looked forward to. You changed how I see learning.'),
     ('From parents', 'With gratitude to [Teacher Name] for the care and patience you give [Student Name] every day.'),
     ('Formal', 'This certificate of appreciation is presented to [Teacher Name] for outstanding dedication to [School] students during [Year].'),
     ('Warm & short', 'Thank you for the years, the energy and the belief. — [Class/Student Name]'),
     ('Milestone', 'Presented to [Teacher Name] for [N] years of inspiring students at [School].')],
    ['<b>Teacher name</b> — the hero of the page.',
     '<b>From</b> — a student, a class, or a parent group.',
     '<b>Why</b> — one specific thing they did that mattered.',
     '<b>Date + school</b> — makes it a keeper.'],
    'What a Thank-You Certificate Needs',
    'Make It Feel Personal',
    ['<b>Name the moment</b> — “the day you stayed after class to help me” beats “for being a great teacher”.',
     '<b>Keep it to one idea</b> — a single sincere sentence lands harder than a paragraph.',
     '<b>Let students write it</b> — handwritten names mean more than printed ones.'],
    [('Is it free?','Yes — the free template is free; premium unlocks for a one-time $9.99.'),
     ('When is Teacher Appreciation Week?','In the US it falls in early May each year — but a thank-you works any day.'),
     ('Can I edit the wording?','Yes — every field is editable, or paste one of the wordings above.'),
     ('Is anything uploaded?','No — everything runs in your browser.')],
    'Make a Teacher Appreciation Certificate Now.',
    'Free to try — no signup, nothing uploaded.'),
]

def render(page):
    html = HEAD
    ld = _ld_for(page)
    extra = '{"@context":"https://schema.org","@type":"WebPage","name":"%s","dateModified":"2026-09-01T00:00:00Z","datePublished":"2026-09-01T00:00:00Z"}' % page['title'].replace('"', '\\"')
    ld_block = ('[%s,%s]' % (ld, extra)) if ld else extra
    subs = {
        '{title}': page['title'], '{meta}': page['meta'], '{slug}': page['slug'],
        '{ldjson}': ld_block, '{h1}': page['h1'], '{hero_p}': page['hero_p'],
        '{tldr}': page['meta'],
        '{sections}': '\n\n'.join(page['sections']),
        '{cta_h2}': page['cta_h2'], '{cta_p}': page['cta_p'],
    }
    for k, v in subs.items():
        if k == '{base}':
            continue
        html = html.replace(k, v)
    html = html.replace('{base}', BASE)
    return html

def related_links(slug):
    items = ['<a href="{base}/certificate-of-completion-template.html">Completion</a>',
             '<a href="{base}/index.html">Certificate Maker</a>']
    for p in PAGES:
        if p['slug'] != slug:
            items.append('<a href="{base}/seo/%s">%s</a>' % (p['slug'], p['h1'].split(' — ')[0].split(' Template')[0]))
    return '\n    '.join(items)

def main():
    seen = set()
    for p in PAGES:
        if p['slug'] in seen:
            print('!! duplicate slug', p['slug']); continue
        seen.add(p['slug'])
        html = render(p)
        html = html.replace('{related}', related_links(p['slug']))
        html = html.replace('{base}', BASE)
        with open(os.path.join(OUT, p['slug']), 'w', encoding='utf-8') as f:
            f.write(html)
        print('wrote', p['slug'], len(html), 'bytes')
    print('done —', len(PAGES), 'pages')

if __name__ == '__main__':
    main()
